IoT/urls.py
from django.conf.urls import *
from IoT.views import  *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'userlogin/$', UserLoginV),
    url(r'userlogout/$', UserLogoutV),
    url(r'accounts/$', UserHomeV),
    url(r'home/$', UserHomeV),
    url(r'userprofile/$',login_required(UserProfileListV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofilelist'),
    url(r'userprofile/(?P<pk>\d+)/$',login_required(UserProfileDetailV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofiledetail'),
    url(r'userprofile/create/$',login_required(UserProfileCreateV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofilecreate'),
    url(r'userprofile/update/(?P<pk>\d+)/$',login_required(UserProfileUpdateV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofileupdate'),
    url(r'userprofile/delete/(?P<pk>\d+)/$',login_required(UserProfileDeleteV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofiledelete'),
    url(r'useraccess/$',login_required(UserAccessListV.as_view(),
    	login_url='/IoT/userlogin/'),name='useraccesslist'),
    url(r'region/$',login_required(RegionListV.as_view(),
    	login_url='/IoT/userlogin/'),name='regionlist'),
    url(r'region/(?P<region_pk>\d+)/$',login_required(RegionDetailV.as_view(),
    	login_url='/IoT/userlogin/'),name='regiondetail'),
    url(r'dev/$',login_required(DevListV.as_view(),
    	login_url='/IoT/userlogin/'),name='devlist'),
    url(r'dev/(?P<dev_pk>\d+)/$',login_required(DevDetailV.as_view(),
    	login_url='/IoT/userlogin/'),name='devdetail'),
    url(r'sensor/$',login_required(SensorListV.as_view(),
    	login_url='/IoT/userlogin/'),name='sensorlist'),
     url(r'sensor/(?P<sensor_pk>\d+)/$',login_required(SensorDetailV.as_view(),
    	login_url='/IoT/userlogin/'),name='sensordetail'),
     url(r'sensorthreshold/$',login_required(SensorThresholdListV.as_view(),
    	login_url='/IoT/userlogin/'),name='sensorthresholdlist'),
     url(r'sensorthreshold/create/(?P<sensor_id>\d+)/$',login_required(SensorThresholdCreateV.as_view(),
    	login_url='/IoT/userlogin/'),name='sensorthresholdcreate'),
     url(r'sensorthreshold/update/(?P<pk>\d+)/$',login_required(SensorThresholdUpdateV.as_view(),
            login_url='/IoT/userlogin/'),name='sensorthresholdupdate'),
     url(r'sensorthreshold/delete/(?P<pk>\d+)/$',login_required(SensorThresholdDeleteV.as_view(),
            login_url='/IoT/userlogin/'),name='sensorthresholddelete'),


     url(r'search/$',SearchV,name='sensorsearch'),
)

mysite/urls.py
from django.conf.urls import url,patterns
from django.contrib import admin
from django.conf.urls import include
from blog.views import *
from django.conf   import   settings
urlpatterns = [
    url(r'^blog/',include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^form/$', login),
    url(r'^IoT/',include('IoT.urls')),
    url(r'^gallery/',include('gallery.urls')),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

IoT/models.py
# -*-  coding: utf-8   -*-
from django.utils import timezone
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import User

#2016/08/04
'''
 准备添加相应的数据模型和数据字段
 
 对于设备模型：
 （1）添加一个设备模型字段文件域
 （2）添加一个UUID字段用来识别相应的设备ID ,起作用和设备编号类似
 （3）添加一个设备图片文件域，用来存储设备实际安装位置
 （4）添加一个存储对于本设备的MQTT 支持的topic名
 
 添加一个MQTT 数据模型
 
 添加一个设备维护记录模型
 
 添加一个存储文件的
 
 添加一个内部成员模型--------------》也可以沿用django提供的用户模型和用户组模型
 
 
 添加一个事件记录模型：
 （1）要有一个必要的事件等级字段
 （2）要有一个必要的事件描述字段
 （3）要有一个必要的所属设备ID 外键
 （4）要有一个时间字段
'''


#下面是在定义域时的一些选项Field options:
#null   如果为True，将会把该域数据存储为NULL
#blank    默认为真，该域允许为空
#choices
#db_column
#db_index
#db_tablespace
#default
#editable
#error_messages
#help_text
#primary_key
#unique
#unique_for_date
#unique_for_month
#unique_for_year
#verbose_name
#validators
#下面是数据库下面定义的模型域类型Field types：
#AutoField
#BigIntegerField
#BinaryField
#BooleanField      用来描述布尔类型的值的
#CharField
#CommaSeparatedIntegerField
#DateField
#DateTimeField
#DecimalField
#DurationField
#EmailField
#FileField
#FilePathField
#FloatField
#ImageField
#IntegerField
#GenericIPAddressField
#NullBooleanField
#PositiveIntegerField
#PositiveSmallIntegerField
#SlugField
#SmallIntegerField
#TextField
#TimeField
#URLField
#UUIDField
#ForeignKey
#ManyToManyField
#OneToOneField
#

#这个模形用来存储用户能够访问的区域和设备的key
class UserAccessM(models.Model):
	user = models.ForeignKey(User,verbose_name = (u'用户'))  #一个用户可以对多个设备或者区域进行访问
	region_or_dev_flag = models.BooleanField(verbose_name=(u'区域'))        #为真则表示是区域访问权限，为假则表示是设备访问权限
	region_access_key = models.CharField(max_length = 40,verbose_name=(u'密钥'))#保存设备访问权限的access_key
	#下面这两个值跟安装的设备的具体区域代码和设备代码有关系
	region_id = models.SmallIntegerField(verbose_name=(u'区域编号'))    #Values from -32768 to 32767 are safe in all databases supported by Django.
	dev_id = models.BigIntegerField(verbose_name=(u'设备编号')) #numbers from -9223372036854775808 to 9223372036854775807
	#下面的是对设备的基本操作权限的设定
	permission_w = models.BooleanField(default=False,verbose_name=(u'写权限'))  #写和修改的权限
	permission_r = models.BooleanField(default=False,verbose_name=(u'读权限'))	  #读的权限
	permission_c = models.BooleanField(default=False,verbose_name=(u'控制权限'))    #控制的权限
	date_time = models.DateTimeField(default=timezone.now,verbose_name=(u'修改时间'))
	def __unicode__(self):
		return  str(self.id)
class UserAAdmin(admin.ModelAdmin):
	list_display=('user','region_or_dev_flag','date_time')
#这个模型用来存储基本的用户扩展信息	
class UserProfileM(models.Model):

	user = models.OneToOneField(User,unique = True,verbose_name = ('用户'))
	phone = models.CharField(max_length = 20,verbose_name=(u'电话号码'))
	job = models.CharField(max_length = 50,blank=True,verbose_name=(u'职位'))         
	section= models.CharField(max_length = 50,blank=True,verbose_name=(u'部门')) 
	job_unit = models.CharField(max_length = 50,blank=True,verbose_name=(u'单位')) 
	def  __unicode__(self):
		return  u'配置文件'

	@models.permalink
	def get_absolute_url(self):
		return ('userprofiledetail',None,{'pk':str(self.id)})
class UserPAdmin(admin.ModelAdmin):
	list_display=('user','phone','job')


# Create your models here.
#Define region model
class  RegionM(models.Model):
	region_id = models.PositiveIntegerField(unique = True,verbose_name=("区域编号"))
	region_info = models.CharField(max_length=50,blank=True,verbose_name=(u'区域描述'))
	region_name = models.CharField(max_length=50,blank=True,verbose_name=(u'区域名称'))
	reserved = models.CharField(max_length=100,blank=True,verbose_name=(u'保留项1'))
	reserved2 = models.CharField(max_length=100,blank=True,verbose_name=(u'保留项2'))
	access_key = models.CharField(max_length=32,blank=True,verbose_name=(u'访问Key'))
	date_time = models.DateTimeField(default=timezone.now,verbose_name=(u'修改时间'))
	region_position=models.CharField(max_length=100,blank=True,verbose_name=(u'GPS坐标'))
	enable=models.BooleanField(default=False,verbose_name=(u'区域使能位'))
	def __unicode__(self):
		return str(self.region_id)
class RegionAdmin(admin.ModelAdmin):
	list_display=('region_id','region_name','date_time')
class DevM(models.Model):
	dev_id = models.PositiveIntegerField(unique = True,verbose_name=(u'设备编号'))
	dev_info = models.CharField(max_length= 200,blank=True,verbose_name=(u'设备描述'))
	region  = models.ForeignKey(RegionM,verbose_name=(u'所属区域'))
	dev_name = models.CharField(max_length=50,blank=True,verbose_name=(u'设备名称'))
	access_key = models.CharField(max_length=32,blank=True,verbose_name=(u'访问Key'))
	dev_sn	=  models.CharField(max_length=48,blank=True,verbose_name=(u'设备序列号'))
	date_time = models.DateTimeField(default=timezone.now,verbose_name=(u'修改时间'))
	dev_position=models.CharField(max_length=100,blank=True,verbose_name=(u'GPS坐标'))
	enable=models.BooleanField(default=False,verbose_name=(u'设备使能位'))
	reserved = models.CharField(max_length=100,blank=True,verbose_name=(u'保留项1'))
	reserved2 = models.CharField(max_length=100,blank=True,verbose_name=(u'保留项2'))
	def __unicode__(self):
		return str(self.dev_id)
class DevAdmin(admin.ModelAdmin):
	list_display=('dev_id','dev_name','access_key')

SENSOR_TYPE=(
		('A',u'电流'),
		('V',u'电压'),
		('T',u'温度'),
		('H',u'湿度'),
		('P',u'压力'),
		('L',u'位置'),
		('Y',u'时间'),
		('F',u'文件'),
		('I',u'消息'),
		('J',u'图片'),
	)
SENSOR_SYMBOL=(
		(u'A',u'安培'),
		(u'kA',u'千安培'),
		(u'V',u'伏特'),
		(u'kV',u'千伏特'),
		(u'℃',u'摄氏度'),
		(u'%',u'百分数'),
		(u'MPa',u'兆帕'),
		(u'kPa',u'千帕'),
		(u'Pa',u'帕'),
		(u'经纬度',u'经纬度'),
		(' ',u'无'),
	)
class SensorM(models.Model):
	sensor_id = models.PositiveIntegerField(unique = True,verbose_name=(u'传感器编号'))
	sensor_info = models.CharField(max_length=200,blank=True,verbose_name=(u'传感器描述'))
	dev = models.ForeignKey(DevM,verbose_name=(u'传感器所属设备'))
	sensor_type = models.CharField(max_length = 10,choices=SENSOR_TYPE,verbose_name=(u'传感器类型'))
	sensor_name = models.CharField(max_length=50,blank=True,verbose_name=(u'传感器名称'))
	date_time = models.DateTimeField(default=timezone.now,verbose_name=(u'修改时间'))
	sensor_position=models.CharField(max_length=100,blank=True,verbose_name=(u'GPS坐标'))
	enable=models.BooleanField(default=False,verbose_name=(u'传感器使能位'))
	data_scale = models.FloatField(verbose_name=(u'数据标度'))
	data_symbol=models.CharField(max_length=20,choices=SENSOR_SYMBOL,verbose_name=(u'数据符号'))
	top_limit=models.FloatField(verbose_name=(u'测量上限'),default=100.0)
	down_limit= models.FloatField(verbose_name=(u'测量下限'),default=0.0)
	reserved = models.CharField(max_length=100,blank=True,verbose_name=(u'保留项1'))
	reserved2 = models.CharField(max_length=100,blank=True,verbose_name=(u'保留项2'))
	def __unicode__(self):
		return str(self.sensor_id)
class SensorAdmin(admin.ModelAdmin):
	list_display=('sensor_id','sensor_type','sensor_name','dev')
class DataM(models.Model):
	date_time = models.DateTimeField(default=timezone.now,verbose_name=(u'采集时间'))
	data = models.FloatField(verbose_name=(u'数据'))
	sensor  = models.ForeignKey(SensorM,verbose_name=(u'数据所属设备'))
class DataAdmin(admin.ModelAdmin):
	pass
class SensorThresholdM(models.Model):
	user = models.ForeignKey(User,verbose_name=(u'所属访问权限文件'))
	sensor_id = models.IntegerField(default=0,verbose_name=(u'传感器编号'))
	threshold_flag = models.BooleanField(default=True,verbose_name=(u'限值标志'))
	threshold = models.DecimalField(max_digits=6,decimal_places=2,default=10,verbose_name=(u'限值'))
	threshold_e = models.BooleanField(default=False,verbose_name=(u'使能位'))
class SensorTAdmin(admin.ModelAdmin):
	list_display=('threshold_flag','threshold','threshold_e')

class UserDevM(models.Model):

	useraccess = models.ManyToManyField(UserAccessM,verbose_name = ('用户'))
	first_name =  models.CharField(max_length = 20,verbose_name=(u'用户名'))
	last_name =  models.CharField(max_length = 20,verbose_name=(u'用户姓'))
	phone = models.CharField(max_length = 20,verbose_name=(u'电话号码'))
	email  = models.EmailField(verbose_name=(u'Email'))
	reserved = models.CharField(max_length=100,blank=True,verbose_name=(u'保留项1'))
	reserved2 = models.CharField(max_length=100,blank=True,verbose_name=(u'保留项2'))
	def  __unicode__(self):
		return  u'文件'
admin.site.register(UserProfileM,UserPAdmin)
admin.site.register(UserAccessM,UserAAdmin)
admin.site.register(SensorM,SensorAdmin)
admin.site.register(DevM,DevAdmin)
admin.site.register(RegionM,RegionAdmin)
admin.site.register(SensorThresholdM,SensorTAdmin)
admin.site.register([DataM,UserDevM])

IoT/forms.py
#coding=utf-8
#forms.py
from django import forms
from IoT.models import  *
INPUT_CLASS = {'class':'form-control col-md-7 col-xs-12'}
DISABLE_INPUT_CLASS = {'class':'form-control col-md-7 col-xs-12' ,'disabled':'disabled'}
READNOLY_INPUT_CLASS = {'class':'form-control col-md-7 col-xs-12','readonly':"readonly"}
CHECKBOX_CLASS = {'class':'form-control col-md-7 col-xs-12 pull-left'}
DATE_INPUT_CLASS = {'class':'date-picker  form-control col-md-7 col-xs-12'}
SELECT2_SINGLE_CLASS={'class':'select2_single  form-control col-md-7 col-xs-12','tabindex':"-1"}
SELECT2_GROUP_CLASS={'class':'select2_group  form-control col-md-7 col-xs-12'}
SELECT2_MULTIPLE_CLASS={'class':'select2_multiple  form-control col-md-7 col-xs-12'}
#UserProfileM
class  UserProfileForm(forms.ModelForm):
	
	def  __init__(self, user, *args, **kwargs):

		super(UserProfileForm,self).__init__(*args, **kwargs)
		self.fields['user'] = forms.ModelChoiceField(
			queryset = User.objects.filter(username=user.username),
			label = "用户",
			required = True,
			help_text = "只能为当前登录的用户",
			error_messages = { 'required': "必须选择一个有效用户"},
			empty_label = "----------",
			widget = forms.Select(attrs=SELECT2_SINGLE_CLASS),
			)
	phone = forms.CharField(
		required = True,
		label = "电话号码",
		help_text = "填写一个电话号码",
		error_messages = {'required': "请设置一个正确的电话号码"},
		widget = forms.TextInput(attrs = INPUT_CLASS),
		)
	job = forms.CharField(
		required = True,
		label = "工作岗位",
		error_messages = {'required': "请填写工作类型"},
		widget = forms.TextInput(attrs = INPUT_CLASS),
		)
	job_unit = forms.CharField(
		required = True,
		label = "工作单位",
		error_messages = {'required': "请填写工作单位"},
		widget = forms.TextInput(attrs = INPUT_CLASS),
		)
	section = forms.CharField(
		required = True,
		label = "部门",
		error_messages = {'required': "请填写工作部门"},
		widget = forms.TextInput(attrs = DATE_INPUT_CLASS),
		)
	class Meta:
		model = UserProfileM
		fields =  '__all__'
#UserAccessM
#RegionM
#DevM
#SensorM
#DataM
#SensorThresholdM
class  SensorThresholdForm(forms.ModelForm):
	def  __init__(self,*args, **kwargs):
		self.user = kwargs.pop('user')
		super(SensorThresholdForm,self).__init__(*args, **kwargs)
		
		self.fields['user'] = forms.ModelChoiceField(
			queryset = User.objects.filter(username=self.user.username),
			label = "用户",
			required = True,
			help_text = "",
			error_messages = { 'required': "必须选择一个有效的用户"},
			empty_label = "----------",
			widget = forms.Select(attrs=SELECT2_SINGLE_CLASS),
			)
		self.fields['sensor_id']= forms.IntegerField(
			required = False,
			label = "传感器编号",
			help_text = "已经自动选择，不需要修改",
			#empty_label = self.sensor_id,
			error_messages = {'required': "请设置该值","invalid":"该值无效，请重新输入"},
			widget = forms.NumberInput(attrs = READNOLY_INPUT_CLASS),
			)
	threshold_flag = forms.BooleanField(
		required = False,
		label = "阈值标志",
		help_text = "为真表示为上限，为假表示为下限",
		#empty_label = True,
		error_messages = {'required': "请设置该值"},
		widget = forms.CheckboxInput(attrs = CHECKBOX_CLASS),
		)
	 
	threshold = forms.DecimalField(
		required = True,
		label = "阈值",
		error_messages = {'required': "请填写阈值"},
		widget = forms.NumberInput(attrs = INPUT_CLASS),
		)
	threshold_e = forms.BooleanField(
		required = False,
		label = "是否使用该阈值",
		#empty_label = True,
		error_messages = {'required': "请"},
		widget = forms.CheckboxInput(attrs = CHECKBOX_CLASS),
		)
	class Meta:
		model = SensorThresholdM
		fields =  '__all__'
#UserDevM
class  TestForm(forms.Form):
	#region_id = models.PositiveIntegerField(verbose_name=("区域编号"))
	region_id = forms.IntegerField(label=u"区域编号",
		widget=forms.TextInput(attrs=INPUT_CLASS))
	#region_info = models.CharField(max_length=50,blank=True,verbose_name=(u'区域描述'))
	region_info = forms.CharField(max_length=50,label=u'区域描述',
		widget=forms.TextInput(attrs=INPUT_CLASS))

	#region_name = models.CharField(max_length=50,blank=True,verbose_name=(u'区域名称'))
	region_name = forms.CharField(max_length=50,label=u'区域名称',
		widget=forms.TextInput(attrs=INPUT_CLASS))
	#reserved = models.CharField(max_length=50,blank=True,verbose_name=(u'保留项'))
	reserved = forms.CharField(max_length=50,label=u'保留项',
		widget=forms.TextInput(attrs=INPUT_CLASS))

	#access_key = models.CharField(max_length=32,blank=True,verbose_name=(u'访问Key'))
	access_key = forms.CharField(max_length=32,label=u'访问Key',
		widget=forms.TextInput(attrs=INPUT_CLASS))
	#date_time = models.DateTimeField(default=timezone.now,verbose_name=(u'修改时间'))
	date_time = forms.DateTimeField(label=u'访问Key',
		widget=forms.DateTimeInput(attrs=INPUT_CLASS))
	class Meta:
		model = UserProfileM
		fields="__all__"

	auto_id = False
	def as_t(self):
		"Returns this form rendered as HTML <p>s."
		return self._html_output(
			normal_row='<div%(html_class_attr)s>%(label)s <div>%(field)s%(help_text)s</div></div>',
			error_row='%s',
			row_ender='</div>',
			help_text_html=' <span class="helptext">%s</span>',
			errors_on_separate_row=True)
	

IoT/templates/sensorthreshold_create_form.html
{%  extends "form_base.html" %}
{%  block title %}配置 {%  endblock %}
{%  block main_content %}   
<div class="row">
	<div  class="col-md-12  col-sm-12  col-xs-12">
		<div  class="x_panel">
			<!--<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x_title-->
			<div class="x_title">
				<h2>
					生成阈值文件
					<!--small>different  from  elements</small-->
				</h2>
				<ul class="nav  navbar-right  panel_toolbox">
					<li>
						<a href="" class="collapse-link">
							<i  class="fa fa-chevron-up"></i>
						</a>
					</li>
					<li  class="dropdown">
						<a href="#" class="dropdown-toggle"  aria-expanded="false" role="button" data-toggle="dropdown">
							<i  class="fa fa-wrench"></i>
						</a>
						<ul   class="dropdown-menu" role="menu">
							<li>
								<a href="#">Settings 1</a>
							</li>
							<li>
								<a href="#">Settings 2</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="" class="close-link">
							<i class="fa  fa-close"></i>
						</a>
					</li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<!--x_title_end>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>-->
			<!--x_content<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-->
			<div  class="x_content">
				<form action="" method="post" class="form-horizontal form-label-left">
					{%  csrf_token %}
					
					{%  for  field  in  form %}
                                    			<div class="form-group">
                                    			<label class="control-label col-md-3 col-sm-3 col-xs-12" for={{ field.id_for_label }}>{{ field.label }} <span class="required">*</span>
                                            		</label>
                                           		 <div  class="col-md-6 col-sm-6 col-xs-12">
                                            		{{ field }}
                                            		<p class="bg-danger">{{ field.errors.as_text }} </p>
                                            		<p class="bg-info">{{ field.help_text }} </p>
                                            		
                                            		</div>
                                            		
                                    			</div>
                                    			{%  endfor %}
                                    			<div class="ln_solid"></div>
                                    			<div class="form-group">
                                            		<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                                		<button type="submit" class="btn btn-primary">生成</button>
                                            		</div>
                                        			</div>
					
				</form>
			</div>
		</div>
	</div>
</div>
{%     endblock %}
{%  block java_script %}
<script type="text/javascript">
            $(function () {
                'use strict';
                var countriesArray = $.map(countries, function (value, key) {
                    return {
                        value: value,
                        data: key
                    };
                });
                // Initialize autocomplete with custom appendTo:
                $('#autocomplete-custom-append').autocomplete({
                    lookup: countriesArray,
                    appendTo: '#autocomplete-container'
                });
            });
        </script>
 <!-- select2 -->
        <script type="text/javascript">
            $(document).ready(function () {
                $(".select2_single").select2({
                    placeholder: "Select a state",
                    allowClear: true
                });
                $(".select2_group").select2({});
                $(".select2_multiple").select2({
                    maximumSelectionLength: 4,
                    placeholder: "With Max Selection limit 4",
                    allowClear: true
                });
            });
        </script>
        <!-- /select2 -->
{%  endblock %}

IoT/templates/userprofile_update_form.html
{%  extends "form_base.html" %}
{%  block title %}配置 {%  endblock %}
{%  block main_content %}   
<div class="row">
	<div  class="col-md-12  col-sm-12  col-xs-12">
		<div  class="x_panel">
			<!--<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<x_title-->
			<div class="x_title">
				<h2>
					更新配置文件
					<!--small>different  from  elements</small-->
				</h2>
				<ul class="nav  navbar-right  panel_toolbox">
					<li>
						<a href="" class="collapse-link">
							<i  class="fa fa-chevron-up"></i>
						</a>
					</li>
					<li  class="dropdown">
						<a href="#" class="dropdown-toggle"  aria-expanded="false" role="button" data-toggle="dropdown">
							<i  class="fa fa-wrench"></i>
						</a>
						<ul   class="dropdown-menu" role="menu">
							<li>
								<a href="#">Settings 1</a>
							</li>
							<li>
								<a href="#">Settings 2</a>
							</li>
						</ul>
					</li>
					<li>
						<a href="" class="close-link">
							<i class="fa  fa-close"></i>
						</a>
					</li>
				</ul>
				<div class="clearfix"></div>
			</div>
			<!--x_title_end>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>-->
			<!--x_content<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<-->
			<div  class="x_content">
				<form action="" method="post" class="form-horizontal form-label-left">
					{%  csrf_token %}
					
					{%  for  field  in  form %}
                                    			<div class="form-group">
                                    			<label class="control-label col-md-3 col-sm-3 col-xs-12" for={{ field.id_for_label }}>{{ field.label }} <span class="required">*</span>
                                            		</label>
                                           		 <div  class="col-md-6 col-sm-6 col-xs-12">
                                            		{{ field }}
                                            		<p class="bg-danger">{{ field.errors.as_text }} </p>
                                            		<p class="bg-info">{{ field.help_text }} </p>
                                            		
                                            		</div>
                                            		
                                    			</div>
                                    			{%  endfor %}
                                    			<div class="ln_solid"></div>
                                    			<div class="form-group">
                                            		<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                                		<button type="submit" class="btn btn-primary">更新</button>
                                            		</div>
                                        			</div>
					
				</form>
			</div>
			<!--x_content_end-->
			 <!--script type="text/javascript">
                        			$(document).ready(function () {
                            		$('#id_section').daterangepicker({
                                			singleDatePicker: true,
                                			calender_style: "picker_4"
                            		}, function (start, end, label) {
                                		console.log(start.toISOString(), end.toISOString(), label);
                            		});
                        			});
                    		</script-->
		</div>
	</div>
</div>
{%     endblock %}
{%  block java_script %}
<script type="text/javascript">
            $(function () {
                'use strict';
                var countriesArray = $.map(countries, function (value, key) {
                    return {
                        value: value,
                        data: key
                    };
                });
                // Initialize autocomplete with custom appendTo:
                $('#autocomplete-custom-append').autocomplete({
                    lookup: countriesArray,
                    appendTo: '#autocomplete-container'
                });
            });
        </script>
 <!-- select2 -->
        <script type="text/javascript">
            $(document).ready(function () {
                $(".select2_single").select2({
                    placeholder: "Select a state",
                    allowClear: true
                });
                $(".select2_group").select2({});
                $(".select2_multiple").select2({
                    maximumSelectionLength: 4,
                    placeholder: "With Max Selection limit 4",
                    allowClear: true
                });
            });
        </script>
        <!-- /select2 -->
{%  endblock %}