IoT/urls.py
from django.conf.urls import *
from IoT.views import  *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'userlogin/$', UserLoginV),
    url(r'userlogout/$', UserLogoutV),
    url(r'accounts/$', UserHomeV),
    url(r'home/$', UserHomeV),
    url(r'userprofile/$',login_required(UserProfileListV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofilelist'),
    url(r'userprofile/(?P<pk>\d+)/$',login_required(UserProfileDetailV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofiledetail'),
    url(r'userprofile/create/$',login_required(UserProfileCreateV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofilecreate'),
    url(r'userprofile/update/(?P<pk>\d+)/$',login_required(UserProfileUpdateV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofileupdate'),
    url(r'userprofile/delete/(?P<pk>\d+)/$',login_required(UserProfileDeleteV.as_view(),
    	login_url='/IoT/userlogin/'),name='userprofiledelete'),
    url(r'useraccess/$',login_required(UserAccessListV.as_view(),
    	login_url='/IoT/userlogin/'),name='useraccesslist'),
    url(r'region/$',login_required(RegionListV.as_view(),
    	login_url='/IoT/userlogin/'),name='regionlist'),
    url(r'region/(?P<region_pk>\d+)/$',login_required(RegionDetailV.as_view(),
    	login_url='/IoT/userlogin/'),name='regiondetail'),
    url(r'dev/$',login_required(DevListV.as_view(),
    	login_url='/IoT/userlogin/'),name='devlist'),
    url(r'dev/(?P<dev_pk>\d+)/$',login_required(DevDetailV.as_view(),
    	login_url='/IoT/userlogin/'),name='devdetail'),
    url(r'sensor/$',login_required(SensorListV.as_view(),
    	login_url='/IoT/userlogin/'),name='sensorlist'),
     url(r'sensor/(?P<sensor_pk>\d+)/$',login_required(SensorDetailV.as_view(),
    	login_url='/IoT/userlogin/'),name='sensordetail'),
     url(r'sensorthreshold/$',login_required(SensorThresholdListV.as_view(),
    	login_url='/IoT/userlogin/'),name='sensorthresholdlist'),
     url(r'sensorthreshold/create/(?P<sensor_id>\d+)/$',login_required(SensorThresholdCreateV.as_view(),
    	login_url='/IoT/userlogin/'),name='sensorthresholdcreate'),
     url(r'sensorthreshold/update/(?P<pk>\d+)/$',login_required(SensorThresholdUpdateV.as_view(),
            login_url='/IoT/userlogin/'),name='sensorthresholdupdate'),
     url(r'sensorthreshold/delete/(?P<pk>\d+)/$',login_required(SensorThresholdDeleteV.as_view(),
            login_url='/IoT/userlogin/'),name='sensorthresholddelete'),


     url(r'search/$',SearchV,name='sensorsearch'),
)

gallery/urls.py
# -*-  coding: utf-8  -*-

from django.conf.urls  import include,url,patterns
from gallery.models  import  *
from gallery.views  import  ItemView,PhtotoDetailView,ItemsView,ItemDetailView
from django.conf   import   settings

urlpatterns = patterns('',
	url(r'index/$', ItemView.as_view(),
		name='index'
		),
	url(r'items/$', ItemsView.as_view(),
		name='item_list'
		),
	url(r'item/(?P<pk>\d+)/$', ItemDetailView.as_view(),
		
		name='item_detail'
		),
	url(r'photos/(?P<pk>\d+)/$', PhtotoDetailView.as_view(),
		
		name='photo_detail'
		),
	)

mysite/urls.py
from django.conf.urls import url,patterns
from django.contrib import admin
from django.conf.urls import include
from blog.views import *
from django.conf   import   settings
urlpatterns = [
    url(r'^blog/',include('blog.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^form/$', login),
    url(r'^IoT/',include('IoT.urls')),
    url(r'^gallery/',include('gallery.urls')),
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

gallery/models.py
# -*-  coding: utf-8  -*-
from django.db import models
from django.contrib import admin
from gallery.fields import ThumbnailImageField

from  django.core.urlresolvers  import  resolve,reverse
# Create your models here.
class Item(models.Model):
	name = models.CharField(max_length=250)
	description = models.TextField()

	class Meta:
		ordering = ['name']

	def  __unicode__(self):
		return self.name
	@models.permalink
	def get_absolute_url(self):
		return ('item_detail',None,{'pk':str(self.id)})

class Photo(models.Model):
	item = models.ForeignKey(Item)
	title = models.CharField(max_length=100)
	image = ThumbnailImageField(upload_to='photos/')
	caption = models.CharField(max_length=250,blank=True)

	class Meta:
		ordering=['title']

	def __unicode__(self):
		return self.title
	@models.permalink
	def get_absolute_url(self):
		return ('photo_detail',None,{'pk':str(self.id)})

class PhotoInline(admin.StackedInline):
	model = Photo

class  ItemAdmin(admin.ModelAdmin):
	inlines= [PhotoInline]

admin.site.register(Item,ItemAdmin)
admin.site.register(Photo)

gallery/views.py
# -*-  coding: utf-8  -*-
from django.shortcuts import render

# Create your views here.
from  django.views.generic.list import  ListView
from  django.views.generic.detail  import  DetailView
from  django.views.generic.base import TemplateView

from  gallery.models  import  Item,Photo

class  ItemView(TemplateView):
	template_name = "index.html"
	def  get_context_data(self,**kwargs):
		context = super(ItemView,self).get_context_data(**kwargs)
		context["item_list"] = Item.objects.all()
		return context

class  ItemsView(ListView):
	template_name = "items_list.html"
	#model = Item
	queryset = Item.objects.all()
	allow_empty = True

class  ItemDetailView(DetailView):
	template_name = "items_detail.html"
	#model = Item
	queryset = Item.objects.all()
	

class  PhtotoDetailView(DetailView):
	template_name = "photos_detail.html"
	#model = Photo
	queryset = Photo.objects.all()
	

gallery/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>Gallery - {% block title %}{% endblock %}</title>
	<meta charset="UTF-8">
	<style type="text/css">
		body{ margin: 30px; font-family: sans-serif; background: #fff;}
		h1 { background: #ccf; padding: 20px;}
		h2 {background: :#ddf ;padding:  10px 20px;}
		h3 {background: #eef; padding: 5px 20px;}
		table{width: 100%;}
		table th { text-align: left;}
	</style>
</head>
<body>
	<h1>Gallery</h1>
	{% block content %}{% endblock %}

</body>
</html>

gallery/templates/index.html
{% extends "base.html" %}

{%  block title %}{%  endblock  %}
{%  block content  %}

<h2>Welcome to the Gallery!</h2>
<p>Here you find pictures of various item.</p>

<h3>Showcase</h3>
<table>
	<tr>
		{%  for item in item_list|slice:":3"  %}
		<td>
			<a href="{{ item.get_absolute_url }}"><b>{{ item.name }}</b><br />
			{%  if  item.photo_set.count  %}
				<img src="{{ item.photo_set.all.0.image.thumb_url  }}" />
			{%  else %}
				<span>No photos (yet)</span>
			{% endif  %}
			</a>
		</td>
		{%  endfor %}
	</tr>
</table>

<p><a href="{%  url 'item_list'  %}">View the full list &raquo;</a></p>

{%  endblock %}

gallery/templates/items_detail.html
{%  extends  "base.html" %}

{%  block title %} {{  object.name   }}{%  endblock %}

{%  block content %}
<p><a href="{%  url  'index'  %}">&laquo; Back to full  listing</a></p>

<h2>{{  object.name   }}</h2>
<p>{{  object.discription  }}</p>
<h3>Photos</h3>
<table>
	<tr>
		<th>Title</th>
		<th>Thumbnail</th>
		<th>Caption</th>
	</tr>
	{% for photo  in  object.photo_set.all %}
	<tr>
		<td><i>{{ photo.title }}</i></td>
		<td>
			
			<a href="{{  photo.get_absolute_url }}">
				<img src="{{  photo.image.thumb_url }}"  />
			</a>
			

		</td>
		<td>{{   photo.caption }}</td>
	</tr>
	{%  endfor  %}
</table>

{%  endblock %}

gallery/templates/items_list.html
{%  extends  "base.html" %}

{%  block title %} Item List{%  endblock %}

{%  block content %}
<p><a href="{%  url  'index'  %}">&laquo; Back to main page</a></p>

<h2>Items</h2>
{%  if  object_list %}
<table>
	<tr>
		<th>Name</th>
		<th>Sample Thumb</th>
		<th>Description</th>
	</tr>
	{% for item  in  object_list %}
	<tr>
		<td><i>{{ item.name }}</i></td>
		<td>
			{%   if   item.photo_set.count  %}
			<a href="{{  item.get_absolute_url }}">
				<img src="{{  item.photo_set.all.0.image.thumb_url }}">
			</a>
			{%  else  %}
			(No photos currently  uploaded)
			{%  endif %}

		</td>
		<td>{{  item.description  }}</td>
	</tr>
	{%  endfor  %}
</table>

{%  else %}
<p>There are currently no  items  to display.</p>
{%  endif  %}

{%  endblock %}

gallery/templates/photos_detail.html
 {%   extends  "base.html"  %}

{%   block title  %}{{  object.item.name }} -  {{  object.title  }}{%  endblock %}

{%  block  content %}

<a href="{{  object.item.get_absolute_url  }}">&laquo; Back to {{  object.item.name }}  detail page</a>

<h2> {{  object.item.name}}   -  {{  object.title }}</h2>
<img src="{{  object.image.url }}"  />
{%   if  object.caption %}<p>{{ object.caption }}</p>{%  endif %}

{%  endblock  %}